apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-container-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-container
  template:
    metadata:
      labels:
        app: react-container
    spec:
      containers:
        - name: react-container
          image: arsanoshin/front:latest
          ports:
            - containerPort: 3000
